#pragma once
enum ERR_BOUND
{
	ERROR_SUCCESS_0 = 0,	//成功
	ERROR_SUCCESS_REPORT,	//成功并回馈客户端

	ERROR_SYS_BEGIN,
	ERROR_SYS_END = 1000,

	ERROR_NET_ERR_BEGIN,		//网络错误
	ERROR_NET_ERR_END = 2000,

	ERROR_ITEM_BEGIN,			//物品错误
	EEROR_ITEM_END = 3000,

	ERROR_SKILL_BEGIN,			//技能错误
	ERROR_SKILL_END = 4000,

	ERROR_CHAT_BEGIN,			//聊天错误
	ERROR_CHAT_END = 4500,

	ERROR_PARTY_BEGIN,			//组队错误
	ERROR_PARTY_END = 5000,

	ERROR_QUEST_BEGIN,
	ERROR_QUEST_END = 5500,

	ERROR_TRADE_BEGIN,
	ERROR_TRADE_END = 5550,

	ERROR_MISC_BEGIN,			//杂项错误号
	ERROR_MISC_END = 5600,

	ERROR_MAP_BEGIN,
	ERROR_MAP_END = 5700,

	ERROR_PET_BEGIN,
	ERROR_PET_END = 5850,

	ERROR_NEED_REPLY_BEGIN,
	ERROR_NEED_REPLY_END = 5900,

	ERROR_EVENT_BEGIN,
	ERROR_EVENT_END = 6000,

	ERROR_FRIEND_BEGIN,
	ERROR_FRIEND_END = 6050,

	ERROR_ARENA_BEGIN,
	ERROR_ARENA_END = 6100,

	ERROR_MAIL_BEGIN,
	ERROR_MAIL_END_ = 6200,

	ERROR_guild_BEGIN,
	ERROR_guild_END = 6250,

	ERROR_FLUNKY_BEGIN,
	ERROR_FLUNKY_END = 6300,

	ERROR_TOLLGATE_BEGIN,
	ERROR_TOLLGATE_END = 6350,

	ERROR_USER_DEF_BEGIN = 100000,

	ERROR_NO_SCENSE_ID = 6400,
};

enum SYS_ERR
{
	SYS_ERR_INSUFFICIENT_MEMORY = ERROR_SYS_BEGIN,	//内存不足 2
	SYS_ERR_READ_CONFIG_ERR,
	SYS_ERR_SQL_EXE_FAIL,				//SQL语句执行失败
	SYS_ERR_CANT_FIND_CHARACTER,		//没有该用户
	SYS_ERR_WRONG_PWD,					//密码错误
	SYS_ERR_UNKOWN_CMD,					//未知命令
	SYS_ERR_DISCONNECT_FROM_WORLD,		//与世界服务器的连接被断开
	SYS_ERR_WRONG_PARSE_FAIL,			//xml解析错误
	SYS_ERR_SEND_FAIL,					//发送数据失败
	SYS_ERR_CANT_FIND_CONNECTION,		//找不到玩家连接
	SYS_ERR_CANT_FIND_WORLD_SERVER,		//找不到世界服务器
	SYS_ERR_MSG_BUILD_TOO_LARGE,		//数据包太大,无法发送
	SYS_ERR_USERDB_CONN_FAIL,			//用户数据库登录失败
	SYS_ERR_WORLDDB_CONN_FAIL,			//世界数据库登录失败
	SYS_ERR_MAPDB_CONN_FAIL,			//地图数据库登录失败
	SYS_ERR_WORLD_RUN_FAIL,				//世界服务器处理服务运行失败
	SYS_ERR_CLIENT_RUN_FAIL,			//客户端处理服务运行失败
	SYS_ERR_CANT_FIND_MAP,				//找不到地图
	SYS_ERR_BUFFER_IS_FULL,				//缓冲区满了
	SYS_ERR_NET_INVALID,				//网络连接无效
	SYS_ERR_CANT_FIND_MONSTER_TMPL,		//找不到怪物模板
	SYS_ERR_NET_CONFIG_CONN_FAIL,		//配置数据库连接被断开
	SYS_ERR_CANT_CREATE_INSTANCE,		//不能创建模板实例
	SYS_ERR_LUA_LOAD_FAILDED,			//LUA脚本加载失败
	SYS_ERR_CANT_FIND_NPC,				//找不到npc
	SYS_ERR_RUN_LUASCRIPT_FAILDED,		//运行LUA脚本失败
	SYS_ERR_CANT_FIND_MONSTER,			//找不到怪物
	SYS_ERR_CANT_FIND_PET,				//打不到宠物
	SYS_ERR_START_TRANSACTION_FAIL,		//无法开始数据库事务
	SYS_ERR_COMMIT_FAIL,				//数据库事务提交失败
	SYS_ERR_ROLLBACK_FAIL,				//数据库事务回滚失败
	SYS_ERR_CANT_FIND_QUEST_TMPL,		//打不到任务模板
	SYS_ERR_CANT_FIND_ITEM_TMPL,		//找不到物品模板
	SYS_ERR_CANT_FIND_BUILD,			//找不到建筑
	SYS_ERR_CANT_FIND_LUA_FUNCTION,		//脚本函数找不到
	SYS_ERR_PARTY_MSG_WRONG_DILIVERY,	//组队消息流程有问题
	SYS_ERR_HOME_SERVER_DOWN,			//homeserver down
	SYS_ERR_SESSION_TIMEOUT,			//登录session 超时
	SYS_ERR_LOGIN_CONN_FAIL,			//登录login server失败
	SYS_ERR_CANT_FIND_SHOP,				//找不到商店
	SYS_ERR_EXIST_UNAME,				//存在相同名称
	SYS_ERR_CANT_FIND_SOUL_TMPL,		//找不到武魂模板
	SYS_ERR_WRONG_TYPE,					//错误的类型
	SYS_ERR_WRONG_MSG_VERSION,			//消息长度和服务器不匹配
	SYS_CANT_FIND_DROP_GROUP,			//找不到掉落组
	SYS_ERR_MULTI_SEND_CONTAINS_FAILTURE,//多次发送有失败情况
	SYS_ERR_CHAR_DATA_ISNT_COMPLETED,	//角色数据没有发送完整
	SYS_ERR_CANT_FIND_SKILL_TMPL,		//找不到技能模板
	SYS_ERR_CANT_FIND_BATTLE,			//找不到战斗实例
	SYS_ERR_CANT_FIND_BUFF_TEMPLATE,	//找不到buff模板
	SYS_ERR_NEW_GUILD,					//引导错误
	SYS_ERR_PENDING_FULL,				//登录队列满了,请稍后再登录
	SYS_ERR_SERVER_FULL,				//已到达最大在线数,请稍后再登录
	SYS_ERR_CANT_FIND_MASTER,			//宠物没有主人息信
	SYS_ERR_BROADCAST_QUEUE_FULL,		//广播消息列表满了,稍后再试
	SYS_ERR_ACCOUNT_FREEZE,				//账号冻结
	SYS_ERR_FORBID_SPEAK,				//禁言
	SYS_ERR_CANT_FIND_FACTION_MAP,		//找不到阵营战地图
	SYS_ERR_MSG_QUEUE_IS_FULL,			//客户端消息队列满了
	SYS_ERR_CHECK_ATHRIZED_FAIL,		//未通授权检测
	SYS_ERR_NOT_YOUR_TURN,				//未轮到你入,不要插队啊...
	SYS_ERR_CHARACTER_FULL,				//角色满了,不能再创建
	SYS_ERR_CANT_FIND_QUEST_GROUP,		//找不到任务组
	SYS_ERR_CANT_FIND_EVENT,			//没有该活动
	SYS_ERR_IS_SAVING_DATA,				//用户数据正在保存中,不能登录
	SYS_ERR_CANT_FIND_SOUL,				//找不到武魂
	SYS_ERR_CANT_FIND_GATE_DATA,		//找不到关卡数据
	SYS_ERR_CURRENCY_COST_ERR,			//扣钱错误,值小于0
	SYS_ERR_CURRENCY_GIVE_ERR,			//给钱错误,值小于0
	SYS_ERR_CANT_FIND_GUILD,			//找不到公会
	SYS_ERR_WRITE_MSG_OUT_BOUND,		//写消息越界
	SYS_ERR_ROOM_FULL,
};
enum {
	GAME_ERR_CANT_FIND_ROOM = ERROR_ITEM_BEGIN,
	GAME_ERR_CARD_INDEX_INVALID,
	GAME_ERR_BAD_HIT,
	GAME_ERR_MSG_NOT_ALLOWED_NOW,
	GAME_ERR_NOT_ENOUGH_CURRENCY,
	GAME_ERR_BINGOED_ALREADY,
	GAME_ERR_NUMBER_INVALID,
	GAME_ERR_CAHRGE_NOT_COMPLETE,
	GAME_ERR_BAD_BINGO,
	GAME_ERR_NOT_ENOUGH_PLAYER,
	GAME_ERR_NO_ROOM,
	GAME_ERR_CONFIG_PARAM_ERR,
	GAME_ERR_JOINED_ALREADY,
	GAME_ERR_NO_SESSION,
	GAME_ERR_SESSION_TIMEOUT,
	GAME_ERR_WRONG_SESSION,
	GAME_ERR_NOT_ENOUGH_BET,
	GAME_ERR_WRONG_PKTARGET,	//错误PK目标
	
	GAME_ERR_WRONG_STATE = 3000,
	GAME_ERR_BANKER_CANT_CHANGE_GAME,
	GAME_ERR_ENTER_GAME_SUCCESS,
	GAME_TOO_MUCH_BET,
	GAME_ERR_DATA,
	GAME_CANT_BET,
	GAME_USER_CANT_FIND,
	GAME_USER_REG_FAIL,
	GAME_USER_PWD_ERROR,
	GAME_USER_IID_REPEAT,
	GAME_USER_NAME_EXIST,
	GAME_BAD_IID,
	GAME_ERR_WRONG_IID,
};
